version: '3.8'

services:
  vxtwitter_dev:
    image: rust:1.74.0-bullseye
    restart: unless-stopped
    tty: true
    volumes:
      - ../:/workspace/vxtwitter
    working_dir: /workspace/vxtwitter